# Generated by Django 3.2.4 on 2021-10-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
