# Generated by Django 3.2.4 on 2021-10-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_participant_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
